### ISSUE TITLE
F1 2000/F1 2001 (and possibly other games) crashes at first screen

### ISSUE THREAD

**Issue by saulfabregwiivc** [pcercuei/lightrec#24]
Like the title says F1 2000 and F1 2001, both from EA (and possibly other games) when trying to play them using Lightrec, they crash on the first copyright screen.

Playing the USA versions of the game.

Tried latest PCSX-ReARMed, latest WiiSX... no luck with these.

Maybe it's related to missing ICache emulation in Lightrec, or something else?
Any fix for these? Thanks ;)

**Comment by saulfabregwiivc** [comment]
Btw, these games mentioned they only work if using Interpreter but they run horribly slow.

**Comment by pcercuei** [comment]
This was fixed recently. They work properly with the latest PCSX-rearmed.

**Comment by saulfabregwiivc** [comment]
Unfortunately it's still crashing at first screen on both PCSX-ReARMed (RetroArch) and WiiSX (PCSXGC).

I updated PCSX-ReARMed (RetroArch) to latest until commit https://github.com/libretro/pcsx_rearmed/commit/80bc142638988fa7ba87aa17af1ccfcfc21d1e99 and still crashes at this screen.

![image](https://github.com/pcercuei/lightrec/assets/66485640/b23f1af7-6414-43a0-b0dd-290d4cafe6ad)
(only tested EA F1 2000 by now)

Am I missing something here?

EDIT: I also tried enabling Instruction Cache emulation in the Options and still no luck.
Again, these games only work on Interpreter...

Also, any way for fix this game also on WiiSX?

**Comment by Ploggy** [comment]
There maybe some confusion going on here.. there's actually 2 F1 2000 games: 
One called Formula One 2000 (by Midway) 
One called F1 2000 (by EA)
The Formula One 2000 by Midway was the game (along with 99 and 2001) that was fixed by you the other day.
The F1 2000 by EA has the an issue described by @saulfabregwiivc it happens on WiiU also, just tested it :)

**Comment by pcercuei** [comment]
Closing this as the issue is outside Lightrec.

**Comment by saulfabregwiivc** [comment]
> Closing this as the issue is outside Lightrec.

Sorry for my question but what it does mean that the problem of F1 2000 (EA) not booting is caused by something else but Lightrec?

Do you have idea whats actually expecting the game to boot?

**Comment by pcercuei** [comment]
> > Closing this as the issue is outside Lightrec.
> 
> Sorry for my question but what it does mean that the problem of F1 2000 (EA) not booting is caused by something else but Lightrec?
> 
> Do you have idea whats actually expecting the game to boot?

I do know exactly why the game is not booting, and that's how I know that it's not a bug in Lightrec.
